### ISSUE TITLE
Sometimes dashboard icons align vertically

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/Launcher#162] opened 2015-11-16 06:51 UTC
By @dan31 at https://github.com/Starcounter/RebelsLounge/issues/8#issuecomment-156815677

>The icons sometimes align vertically (also applies to Starcounter's Launcher)

Sometimes dashboard icons align vertically instead of horizontally.

**Comment by miyconst** [comment] 2015-11-16 06:52
I saw such behavior a couple of times when there was a bug in `juicy-html`, the bug was fixed and since that time I was not able to reproduce this issue.

Things to do:

- Check whether any of the apps include old version of `juicy-html`
- Check console for any errors next time this happens

**Comment by miyconst** [comment] 2015-11-16 09:30
By @dan31 

> Guys @miyconst @warpech @andwah , that one is important, we see it all the time:

What I mean is this:
<img width="449" alt="screen shot 2015-11-16 at 10 21 59" src="https://cloud.githubusercontent.com/assets/7162535/11178309/4633ed24-8c4c-11e5-931a-63b8f46b7d9b.png">
It happens time to time when one hits the Back button.

**Comment by warpech** [comment] 2015-11-16 11:15
Reproducible with StarcounterSamples Launcher + People + Products

1. Install and run Launcher, People, Products
2. Go to list of Products (localhost:8080/products)
3. Click on the Launcher Home icon

Result:

<img width="835" alt="screenshot 2015-11-16 12 15 04" src="https://cloud.githubusercontent.com/assets/566463/11180540/b6dc9c2e-8c5b-11e5-83fc-217a9bc786e4.png">

**Comment by tomalec** [comment] 2015-11-16 11:38
As I suspected it happens because `launcher-launchpad` is loaded for the first time inside hidden container, therefore it does have width `0` and there is no `refresh` once shown. In other cases (partials in apps) it works as pages does have first break point specified in layout, but there is no layout for launchpad.

**Comment by warpech** [comment] 2015-11-16 12:06
So, how to fix this?

**Comment by tomalec** [comment] 2015-11-16 12:07
I'm still working on it. That's was just a note for future references to similar issues :)

**Comment by tomalec** [comment] 2015-11-16 14:17
I think we need to decide on what we would like to achive, as the root of a problem is the fact that launchpad is attached in background, into hidden (`display: none`) container, so it packs things into `0,0`, then it's being revealed (`display: block` on parent container) by `display-router`

The question is how we would like this instance of `juicy-tile-grid` to adapt to such behavior?

I can see two ways to go:
1. Process layout according to current windows size in background, then once router reveals parent container, it's already there and just browser needs to handle it.
2. Pack everything to `0,0` as currently when loaded, then once revealed it needs to process the layout according to the new dimensions of a container.
3. Do not use `juicy-tile-grid` for launchpad, replace it with just flexbox/sortable flexbox

Both has pros, and cons and side-stories.
## 1. Pre-process in background
Pros:
 + we can use existing first-break point functionality, and provide arbitrary width to pack items,
 + improves UX on routing

Cons
 - affects initial load time (exactly as currently)
 - if user 
  1. Opens the App's workspace,
  2. Re-sizes the window beyond breakpoint,
  3. Navigates to launchpad

  he/she will end up once again with wrong layout

## 2 Refresh on reveal
 Pros
+ we may do nothing if `juicy-tile-grid` width or height is `0` (needs to be implemented) what would improve performance of JS calculations running for hidden elements,
+ we may use existing `refreshonresize`.. but.. see below

Cons
- if we will use `refreshonresize` functionality it will refresh it also for other re-sizes (currently even when hidden), so it hits back performance and UX
- it's hard to identify such "reveal" event,
- we may rely on events triggered by `juicy-display-router` but then we will still have this issue for other cases

## 3 Remove `juicy-tile-grid`

Pros
+ easiest,
+ fastest
Cons
- does not allow users to modify the layout (unless we will use `sortable-flexbox-list` which needs to be updated to new Polymer and refreshed in general),
- does not let us create good looking, responsive grids of app icons
- the problem will persist for other places.

## Side notes
If we would like to keep `juicy-tile-grid`, it would be nice to make it editable with the same UI as others.
I will create a separated issue for that and fix it, once we will agree that we want it

**Comment by dan31** [comment] 2015-11-16 14:42
A note that @miyconst missed: we need the fix by tomorrow for the demo.

**Comment by tomalec** [comment] 2015-11-16 14:52
I can provide quick fix in any of those 3 direction within 30mins, I just want to agree what fits us best, and where to go with long term solution.

If we are going to re-size a lot during a demo, I suggest 2 or 3, if we would bother about fluent performance: 2 or 3, if customization: 1 or 2.

**Comment by warpech** [comment] 2015-11-16 15:22
With Tomek we decided on 1, for the reasons explained in that point.

**Comment by tomalec** [comment] 2015-11-16 19:25
I will close this issue, as a (quick) fix for original problem was already pushed. Moreover, I would prefer to postpone long-term solution implementation after the [Wednesday demo](https://github.com/Starcounter/RebelsLounge/issues/8), as it requires to change `juicy-tile-list`, `juicy-tile-editor`, ugly work around for Starcounter/Starcounter/issues/3072, and may led the demo to https://github.com/Starcounter/Starcounter/issues/3074

I will push my changes to separated branches and track further development at #164

**Closed by tomalec** 2015-11-16 19:25 UTC
Labels: bug
